import type { AppProps } from 'next/app'
import Head from 'next/head'

import { CommonThemeProvider } from '@/components/mui/ThemeProvider'

import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <CommonThemeProvider>
      <Head>
        <title>FreshFinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </CommonThemeProvider>
  )
}
